name: Tests

on: [push, pull_request]

jobs:
  Tests:
    runs-on: ubuntu-latest
    container: guerra1994/go-docker-mqtt-ubuntu-env

    steps:
      - name: check out code
        uses: actions/checkout@v2

      - name: run functional test
        run: ./scripts/functional-tests.sh

      - name: run install tests
        run: ./scripts/install-tests.sh
