name: Tests

on: [push, pull_request]

jobs:
  Tests:
    runs-on: ubuntu-latest
    container: guerra1994/go-docker-mqtt-ubuntu-env

    steps:
      - name: check out code
        uses: actions/checkout@v2

      - name: run docker tests
        run: ./scripts/docker-tests.sh

      - name: run auth tests
        run: go test -v ./auth

      - name: run apt tests
        run: ./scripts/apt-tests.sh
